# Generated by Django 3.1.7 on 2021-03-30 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20210330_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_purchased',
            name='bus_time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 30, 13, 10, 16, 968651)),
        ),
    ]
